from __future__ import annotations

from models import ConfigSpec, spec


CONFIG_SPECS: tuple[ConfigSpec, ...] = (
    spec("", "include", "string", "", True),
    spec("", "show_link", "array/string", "[]", False),
    spec("", "default_dc", "integer", "", False),
    spec("", "beobachten", "boolean", True, False),
    spec("", "beobachten_minutes", "integer", 10, False),
    spec("", "beobachten_flush_secs", "integer", 15, False),
    spec("", "beobachten_file", "string", "cache/beobachten.txt", False),
    spec("logging", "destination", "enum", "stderr", False, ("stderr", "syslog", "file")),
    spec("logging", "path", "string", "", False),
    spec("logging", "rotation", "enum", "never", False, ("never", "minutely", "hourly", "daily", "weekly")),
    spec("logging", "max_size_bytes", "integer", 0, False),
    spec("logging", "max_files", "integer", 0, False),
    spec("logging", "max_age_secs", "integer", 0, False),
    spec("general", "data_path", "string", "", False),
    spec("general", "quota_state_path", "string", "telemt.limit.json", False),
    spec("general", "config_strict", "boolean", False, False),
    spec("general", "prefer_ipv6", "boolean", False, False),
    spec("general", "fast_mode", "boolean", True, False),
    spec("general", "use_middle_proxy", "boolean", True, False),
    spec("general", "proxy_secret_path", "string", "proxy-secret", False),
    spec("general", "proxy_secret_url", "string", "https://core.telegram.org/getProxySecret", False),
    spec("general", "proxy_config_v4_cache_path", "string", "cache/proxy-config-v4.txt", False),
    spec("general", "proxy_config_v4_url", "string", "https://core.telegram.org/getProxyConfig", False),
    spec("general", "proxy_config_v6_cache_path", "string", "cache/proxy-config-v6.txt", False),
    spec("general", "proxy_config_v6_url", "string", "https://core.telegram.org/getProxyConfigV6", False),
    spec("general", "ad_tag", "string", "", True),
    spec("general", "middle_proxy_nat_ip", "string", "", False),
    spec("general", "middle_proxy_nat_probe", "boolean", True, False),
    spec("general", "middle_proxy_nat_stun", "string", "", False),
    spec("general", "middle_proxy_nat_stun_servers", "array", "[]", False),
    spec("general", "stun_nat_probe_concurrency", "integer", 8, False),
    spec("general", "middle_proxy_pool_size", "integer", 8, False),
    spec("general", "middle_proxy_warm_standby", "integer", 16, False),
    spec("general", "me_init_retry_attempts", "integer", 0, False),
    spec("general", "me2dc_fallback", "boolean", True, False),
    spec("general", "me2dc_fast", "boolean", False, False),
    spec("general", "me_keepalive_enabled", "boolean", True, False),
    spec("general", "me_keepalive_interval_secs", "integer", 8, False),
    spec("general", "me_keepalive_jitter_secs", "integer", 2, False),
    spec("general", "me_keepalive_payload_random", "boolean", True, False),
    spec("general", "rpc_proxy_req_every", "integer", 0, False),
    spec("general", "me_writer_cmd_channel_capacity", "integer", 4096, False),
    spec("general", "me_route_channel_capacity", "integer", 768, False),
    spec("general", "me_c2me_channel_capacity", "integer", 1024, False),
    spec("general", "me_c2me_send_timeout_ms", "integer", 4000, False),
    spec("general", "me_reader_route_data_wait_ms", "integer", 2, True),
    spec("general", "me_d2c_flush_batch_max_frames", "integer", 32, True),
    spec("general", "me_d2c_flush_batch_max_bytes", "integer", 131072, True),
    spec("general", "me_d2c_flush_batch_max_delay_us", "integer", 500, True),
    spec("general", "me_d2c_ack_flush_immediate", "boolean", True, True),
    spec("general", "me_quota_soft_overshoot_bytes", "integer", 65536, True),
    spec("general", "me_d2c_frame_buf_shrink_threshold_bytes", "integer", 262144, True),
    spec("general", "direct_relay_copy_buf_c2s_bytes", "integer", 65536, True),
    spec("general", "direct_relay_copy_buf_s2c_bytes", "integer", 262144, True),
    spec("general", "crypto_pending_buffer", "integer", 262144, False),
    spec("general", "max_client_frame", "integer", 16777216, False),
    spec("general", "desync_all_full", "boolean", False, True),
    spec("general", "hardswap", "boolean", True, True),
    spec("general", "log_level", "enum", "normal", True, ("debug", "verbose", "normal", "silent")),
    spec("general", "disable_colors", "boolean", False, False),
    spec("general", "update_every", "integer", 300, True),
    spec("general", "ntp_check", "boolean", True, False),
    spec("general", "ntp_servers", "array", '["pool.ntp.org"]', False),
    spec("general", "auto_degradation_enabled", "boolean", True, False),
    spec("general", "rst_on_close", "enum", "off", False, ("off", "errors", "always")),
    spec("general.modes", "classic", "boolean", False, False),
    spec("general.modes", "secure", "boolean", False, False),
    spec("general.modes", "tls", "boolean", False, False),
    spec("general.links", "show", "array/string", "[]", False),
    spec("general.links", "public_host", "string", "", False),
    spec("general.links", "public_port", "integer", 443, False),
    spec("general.telemetry", "enabled", "boolean", True, True),
    spec("general.telemetry", "max_users", "integer", 20000, True),
    spec("general.telemetry", "user_idle_ttl_secs", "integer", 86400, True),
    spec("general.telemetry", "user_sweep_interval_secs", "integer", 300, True),
    spec("network", "prefer", "enum", "auto", False, ("auto", "4", "6")),
    spec("network", "stun_use", "boolean", True, False),
    spec("network", "stun_servers", "array", "[]", False),
    spec("server", "listen", "string", "", False),
    spec("server", "listen_addr_ipv4", "string", "0.0.0.0", False),
    spec("server", "listen_addr_ipv6", "string", "::", False),
    spec("server", "port", "integer", 443, False),
    spec("server", "listen_unix_sock", "string", "", False),
    spec("server", "listen_unix_sock_perm", "string", "", False),
    spec("server", "listen_tcp", "boolean", "", False),
    spec("server", "client_mss", "string", "", False),
    spec("server", "client_mss_bulk", "string", "", False),
    spec("server", "proxy_protocol", "boolean", False, False),
    spec("server", "proxy_protocol_header_timeout_ms", "integer", 500, False),
    spec("server", "proxy_protocol_trusted_cidrs", "array", "trust-all", False),
    spec("server", "metrics_port", "integer", "", False),
    spec("server", "metrics_listen", "string", "", False),
    spec("server", "metrics_whitelist", "array", "[]", False),
    spec("server", "max_connections", "integer", 0, False),
    spec("server", "accept_permit_timeout_ms", "integer", 0, False),
    spec("server.conntrack_control", "inline_conntrack_control", "boolean", True, False),
    spec("server.conntrack_control", "mode", "enum", "tracked", False, ("tracked", "notrack", "hybrid")),
    spec("server.conntrack_control", "backend", "enum", "auto", False, ("auto", "nftables", "iptables")),
    spec("server.conntrack_control", "profile", "enum", "balanced", False, ("conservative", "balanced", "aggressive")),
    spec("server.conntrack_control", "hybrid_listener_ips", "array", "[]", False),
    spec("server.conntrack_control", "pressure_high_watermark_pct", "integer", 85, False),
    spec("server.conntrack_control", "pressure_low_watermark_pct", "integer", 70, False),
    spec("server.conntrack_control", "delete_budget_per_sec", "integer", 4096, False),
    spec("server.api", "enabled", "boolean", True, False),
    spec("server.api", "listen", "string", "0.0.0.0:9091", False),
    spec("server.api", "whitelist", "array", '["127.0.0.0/8"]', False),
    spec("server.api", "auth_header", "string", "", False),
    spec("server.api", "request_body_limit_bytes", "integer", 65536, False),
    spec("server.api", "minimal_runtime_enabled", "boolean", True, False),
    spec("server.api", "minimal_runtime_cache_ttl_ms", "integer", 1000, False),
    spec("server.api", "runtime_edge_enabled", "boolean", False, False),
    spec("server.api", "runtime_edge_cache_ttl_ms", "integer", 1000, False),
    spec("server.api", "runtime_edge_top_n", "integer", 10, False),
    spec("server.api", "runtime_edge_events_capacity", "integer", 256, False),
    spec("server.api", "read_only", "boolean", False, False),
    spec("server.api", "gray_action", "enum", "drop", False, ("drop", "api", "200")),
    spec("timeouts", "client_first_byte_idle_secs", "integer", 300, False),
    spec("timeouts", "relay_idle_policy_v2_enabled", "boolean", True, False),
    spec("timeouts", "relay_client_idle_soft_secs", "integer", 120, False),
    spec("timeouts", "relay_client_idle_hard_secs", "integer", 360, False),
    spec("timeouts", "relay_idle_grace_after_downstream_activity_secs", "integer", 30, False),
    spec("timeouts", "client_keepalive", "integer", 15, False),
    spec("timeouts", "client_ack", "integer", 90, False),
    spec("timeouts", "me_one_retry", "integer", 12, False),
    spec("timeouts", "me_one_timeout_ms", "integer", 1200, False),
    spec("censorship", "tls_domain", "string", "petrovich.ru", False),
    spec("censorship", "tls_domains", "array", "[]", False),
    spec("censorship", "unknown_sni_action", "enum", "drop", False, ("drop", "mask", "accept", "reject_handshake")),
    spec("censorship", "tls_fetch_scope", "string", "", False),
    spec("censorship", "mask", "boolean", True, False),
    spec("censorship", "mask_host", "string", "", False),
    spec("censorship", "mask_port", "integer", 443, False),
    spec("censorship", "mask_unix_sock", "string", "", False),
    spec("censorship", "fake_cert_len", "integer", 2048, False),
    spec("censorship", "tls_emulation", "boolean", True, False),
    spec("censorship", "tls_front_dir", "string", "tlsfront", False),
    spec("censorship", "server_hello_delay_min_ms", "integer", 0, False),
    spec("censorship", "server_hello_delay_max_ms", "integer", 0, False),
    spec("censorship", "tls_new_session_tickets", "integer", 0, False),
    spec("censorship", "tls_full_cert_ttl_secs", "integer", 90, False),
    spec("censorship", "serverhello_compact", "boolean", False, False),
    spec("censorship", "alpn_enforce", "boolean", True, False),
    spec("censorship", "mask_proxy_protocol", "integer", 0, False),
    spec("censorship", "mask_shape_hardening", "boolean", True, False),
    spec("censorship", "mask_shape_hardening_aggressive_mode", "boolean", False, False),
    spec("censorship", "mask_shape_bucket_floor_bytes", "integer", 512, False),
    spec("censorship", "mask_shape_bucket_cap_bytes", "integer", 4096, False),
    spec("censorship", "mask_shape_above_cap_blur", "boolean", False, False),
    spec("censorship", "mask_shape_above_cap_blur_max_bytes", "integer", 512, False),
    spec("censorship", "mask_relay_max_bytes", "integer", 5242880, False),
    spec("censorship", "mask_relay_timeout_ms", "integer", 60000, False),
    spec("censorship", "mask_relay_idle_timeout_ms", "integer", 5000, False),
    spec("censorship", "mask_classifier_prefetch_timeout_ms", "integer", 5, False),
    spec("censorship", "mask_timing_normalization_enabled", "boolean", False, False),
    spec("censorship", "mask_timing_normalization_floor_ms", "integer", 0, False),
    spec("censorship", "mask_timing_normalization_ceiling_ms", "integer", 0, False),
    spec("censorship.tls_fetch", "profiles", "array", '["modern_chrome_like", "modern_firefox_like", "compat_tls12", "legacy_minimal"]', False),
    spec("censorship.tls_fetch", "strict_route", "boolean", True, False),
    spec("censorship.tls_fetch", "attempt_timeout_ms", "integer", 5000, False),
    spec("censorship.tls_fetch", "total_budget_ms", "integer", 15000, False),
    spec("censorship.tls_fetch", "grease_enabled", "boolean", False, False),
    spec("censorship.tls_fetch", "deterministic", "boolean", False, False),
    spec("censorship.tls_fetch", "profile_cache_ttl_secs", "integer", 600, False),
    spec("access", "user_max_tcp_conns_global_each", "integer", 0, True),
    spec("access", "user_max_unique_ips_global_each", "integer", 0, True),
    spec("access", "user_max_unique_ips_mode", "enum", "active_window", True, ("active_window", "time_window", "combined")),
    spec("access", "user_max_unique_ips_window_secs", "integer", 30, True),
    spec("access", "replay_check_len", "integer", 65536, False),
    spec("access", "replay_window_secs", "integer", 120, False),
    spec("access", "ignore_time_skew", "boolean", False, False),
)

